package configgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/Palasito/go-smtp/internal/config"
)

// GenerateEnvTemplate writes a fully-commented .env template to w.
func GenerateEnvTemplate(w io.Writer) error {
	if _, err := fmt.Fprintf(w, "# ============================================================\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "# smtp-relay configuration\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "# Generated by: smtp-relay generate\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "# ============================================================\n"); err != nil {
		return err
	}

	for _, group := range config.Groups() {
		if _, err := fmt.Fprintf(w, "\n# === %s ===\n\n", group); err != nil {
			return err
		}
		for _, f := range config.FieldsByGroup(group) {
			if _, err := fmt.Fprintf(w, "# %s\n", f.Description); err != nil {
				return err
			}
			if len(f.ValidValues) > 0 {
				if _, err := fmt.Fprintf(w, "# Valid values: %s\n", strings.Join(f.ValidValues, ", ")); err != nil {
					return err
				}
			} else if f.ValidationHint != "" {
				if _, err := fmt.Fprintf(w, "# Hint: %s\n", f.ValidationHint); err != nil {
					return err
				}
			}
			if f.ConditionallyRequired != "" {
				if _, err := fmt.Fprintf(w, "# Note: %s\n", f.ConditionallyRequired); err != nil {
					return err
				}
			}
			val := f.Default
			if f.Sensitive {
				val = "CHANGE_ME"
			}
			if _, err := fmt.Fprintf(w, "# %s=%s\n", f.EnvVar, val); err != nil {
				return err
			}
			if _, err := fmt.Fprintf(w, "\n"); err != nil {
				return err
			}
		}
	}
	return nil
}

// GenerateComposeTemplate writes a docker-compose.yml template to w.
func GenerateComposeTemplate(w io.Writer) error {
	header := `# ============================================================
# smtp-relay docker-compose configuration
# Generated by: smtp-relay generate
# ============================================================

services:
  smtp-relay:
    image: ghcr.io/palasito/go-smtp:latest
    container_name: smtp-relay
    # Must be >= SHUTDOWN_TIMEOUT so Docker does not SIGKILL before the drain completes.
    stop_grace_period: 35s
    restart: unless-stopped
    ports:
      - "8025:8025"   # SMTP
      - "9090:9090"   # Health/Metrics
    volumes:
      - ./certs:/certs:ro
      - ./logs:/logs
    environment:
`
	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}

	for _, group := range config.Groups() {
		if _, err := fmt.Fprintf(w, "      # === %s ===\n\n", group); err != nil {
			return err
		}
		for _, f := range config.FieldsByGroup(group) {
			if _, err := fmt.Fprintf(w, "      # %s\n", f.Description); err != nil {
				return err
			}
			if len(f.ValidValues) > 0 {
				if _, err := fmt.Fprintf(w, "      # Valid values: %s\n", strings.Join(f.ValidValues, ", ")); err != nil {
					return err
				}
			} else if f.ValidationHint != "" {
				if _, err := fmt.Fprintf(w, "      # Hint: %s\n", f.ValidationHint); err != nil {
					return err
				}
			}
			if f.ConditionallyRequired != "" {
				if _, err := fmt.Fprintf(w, "      # Note: %s\n", f.ConditionallyRequired); err != nil {
					return err
				}
			}
			val := f.Default
			if f.Sensitive {
				val = "CHANGE_ME"
			}
			if _, err := fmt.Fprintf(w, "      # %s: \"%s\"\n", f.EnvVar, val); err != nil {
				return err
			}
			if _, err := fmt.Fprintf(w, "\n"); err != nil {
				return err
			}
		}
	}
	return nil
}
