package configgen

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"github.com/Palasito/go-smtp/internal/config"
	"golang.org/x/term"
)

// RunWizard interactively prompts the user for each config field and writes
// the result to w in the specified format ("env" or "compose").
// It reads user input from stdin.
func RunWizard(w io.Writer, format string) error {
	scanner := bufio.NewScanner(os.Stdin)
	values := make(map[string]string)

	// Initialize all values with defaults
	for _, f := range config.Schema {
		values[f.EnvVar] = f.Default
	}

	for _, group := range config.Groups() {
		fields := config.FieldsByGroup(group)

		fmt.Fprintf(os.Stderr, "\n=== %s Configuration ===\n\n", group)
		fmt.Fprintf(os.Stderr, "Configure %s settings? [Y/n]: ", group)

		scanner.Scan()
		answer := strings.TrimSpace(scanner.Text())
		if strings.EqualFold(answer, "n") {
			fmt.Fprintf(os.Stderr, "  Skipping %s (using defaults)\n", group)
			continue
		}

		for _, f := range fields {
			fmt.Fprintf(os.Stderr, "  %s\n", f.Description)
			if len(f.ValidValues) > 0 {
				fmt.Fprintf(os.Stderr, "  Valid: %s\n", strings.Join(f.ValidValues, ", "))
			}
			if f.ValidationHint != "" && len(f.ValidValues) == 0 {
				fmt.Fprintf(os.Stderr, "  Hint: %s\n", f.ValidationHint)
			}

			var input string
			maxRetries := 3

			for attempt := 0; attempt <= maxRetries; attempt++ {
				if attempt > 0 {
					fmt.Fprintf(os.Stderr, "  %s [%s]: ", f.EnvVar, f.Default)
				} else {
					fmt.Fprintf(os.Stderr, "  %s [%s]: ", f.EnvVar, f.Default)
				}

				if f.Sensitive {
					// Try masked password input
					raw, err := term.ReadPassword(int(os.Stdin.Fd()))
					fmt.Fprintln(os.Stderr) // newline after masked input
					if err != nil {
						// Fallback to scanner
						scanner.Scan()
						input = strings.TrimSpace(scanner.Text())
					} else {
						input = strings.TrimSpace(string(raw))
					}
				} else {
					scanner.Scan()
					input = strings.TrimSpace(scanner.Text())
				}

				// Empty input = use default
				if input == "" {
					input = f.Default
					break
				}

				// Validate
				if err := validateFieldInput(f, input); err != nil {
					if attempt < maxRetries {
						fmt.Fprintf(os.Stderr, "  ✗ Invalid: %s\n", err)
						continue
					}
					fmt.Fprintf(os.Stderr, "  ⚠ Max retries reached, using default: %s\n", f.Default)
					input = f.Default
				}
				break
			}

			values[f.EnvVar] = input
		}
	}

	// Print summary of non-default values
	fmt.Fprintf(os.Stderr, "\n=== Summary (non-default values) ===\n\n")
	hasChanges := false
	for _, f := range config.Schema {
		if values[f.EnvVar] != f.Default {
			if f.Sensitive {
				fmt.Fprintf(os.Stderr, "  %s = ****\n", f.EnvVar)
			} else {
				fmt.Fprintf(os.Stderr, "  %s = %s\n", f.EnvVar, values[f.EnvVar])
			}
			hasChanges = true
		}
	}
	if !hasChanges {
		fmt.Fprintf(os.Stderr, "  (all defaults)\n")
	}
	fmt.Fprintln(os.Stderr)

	// Write output
	if format == "compose" {
		containerName := "smtp-relay"
		fmt.Fprintf(os.Stderr, "\nContainer name [%s]: ", containerName)
		scanner.Scan()
		if cn := strings.TrimSpace(scanner.Text()); cn != "" {
			containerName = cn
		}
		return writeComposeWithValues(w, values, containerName)
	}
	return writeEnvWithValues(w, values)
}

func validateFieldInput(f config.FieldDef, input string) error {
	// Enum check
	if len(f.ValidValues) > 0 {
		found := false
		for _, v := range f.ValidValues {
			if strings.EqualFold(v, input) {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("must be one of: %s", strings.Join(f.ValidValues, ", "))
		}
	}

	// Type check
	switch f.Type {
	case "int":
		if _, err := strconv.Atoi(input); err != nil {
			return fmt.Errorf("must be a valid integer")
		}
	case "int64":
		if _, err := strconv.ParseInt(input, 10, 64); err != nil {
			return fmt.Errorf("must be a valid integer")
		}
	case "bool":
		lower := strings.ToLower(input)
		if lower != "true" && lower != "false" {
			return fmt.Errorf("must be \"true\" or \"false\"")
		}
	}

	return nil
}

// writeEnvWithValues writes .env format with user-provided values uncommented.
func writeEnvWithValues(w io.Writer, values map[string]string) error {
	fmt.Fprintln(w, "# ============================================================")
	fmt.Fprintln(w, "# smtp-relay configuration")
	fmt.Fprintln(w, "# Generated by: smtp-relay generate --interactive")
	fmt.Fprintln(w, "# ============================================================")

	for _, group := range config.Groups() {
		fmt.Fprintf(w, "\n# === %s ===\n\n", group)
		for _, f := range config.FieldsByGroup(group) {
			fmt.Fprintf(w, "# %s\n", f.Description)
			val := values[f.EnvVar]
			if val != f.Default {
				// User changed this value — uncommented
				fmt.Fprintf(w, "%s=%s\n", f.EnvVar, val)
			} else {
				// Default — commented out
				if f.Sensitive {
					fmt.Fprintf(w, "# %s=<CHANGE_ME>\n", f.EnvVar)
				} else {
					fmt.Fprintf(w, "# %s=%s\n", f.EnvVar, f.Default)
				}
			}
			fmt.Fprintln(w)
		}
	}
	return nil
}

// writeComposeWithValues writes docker-compose.yml with user-provided values uncommented.
func writeComposeWithValues(w io.Writer, values map[string]string, containerName string) error {
	fmt.Fprintln(w, "# ============================================================")
	fmt.Fprintln(w, "# smtp-relay docker-compose configuration")
	fmt.Fprintln(w, "# Generated by: smtp-relay generate --interactive")
	fmt.Fprintln(w, "# ============================================================")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "services:")
	fmt.Fprintln(w, "  smtp-relay:")
	fmt.Fprintln(w, "    image: ghcr.io/palasito/go-smtp:latest")
	fmt.Fprintf(w, "    container_name: %s\n", containerName)
	fmt.Fprintln(w, "    # Must be >= SHUTDOWN_TIMEOUT so Docker does not SIGKILL before the drain completes.")
	fmt.Fprintln(w, "    stop_grace_period: 35s")
	fmt.Fprintln(w, "    restart: unless-stopped")
	fmt.Fprintln(w, "    ports:")
	fmt.Fprintln(w, `      - "8025:8025"   # SMTP`)
	fmt.Fprintln(w, `      - "9090:9090"   # Health/Metrics`)
	fmt.Fprintln(w, "    volumes:")
	fmt.Fprintln(w, "      - ./certs:/certs:ro")
	fmt.Fprintln(w, "      - ./logs:/logs")
	fmt.Fprintln(w, "    environment:")

	for _, group := range config.Groups() {
		fmt.Fprintf(w, "      # === %s ===\n\n", group)
		for _, f := range config.FieldsByGroup(group) {
			fmt.Fprintf(w, "      # %s\n", f.Description)
			val := values[f.EnvVar]
			if val != f.Default {
				fmt.Fprintf(w, "      %s: \"%s\"\n", f.EnvVar, val)
			} else {
				if f.Sensitive {
					fmt.Fprintf(w, "      # %s: \"<CHANGE_ME>\"\n", f.EnvVar)
				} else {
					fmt.Fprintf(w, "      # %s: \"%s\"\n", f.EnvVar, f.Default)
				}
			}
			fmt.Fprintln(w)
		}
	}
	return nil
}
